name: NVHPC Matrix Test

on:
  push:
    branches:
      - main

jobs:
  nvhpc-25-1-default-run-1:
    name: NVHPC 25.1 / default / run 1
    uses: ./.github/workflows/nvhpc-test.yml
    with: &nvhpc_25_1_default
      nvhpc: "25.1"
      image: nvcr.io/nvidia/nvhpc:25.1-devel-cuda12.6-ubuntu22.04
      variant: default
      compile_flags: ""
      run_env: ""

  nvhpc-25-1-default-run-2:
    name: NVHPC 25.1 / default / run 2
    needs: nvhpc-25-1-default-run-1
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_default

  nvhpc-25-1-default-run-3:
    name: NVHPC 25.1 / default / run 3
    needs: nvhpc-25-1-default-run-2
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_default

  nvhpc-25-1-default-run-4:
    name: NVHPC 25.1 / default / run 4
    needs: nvhpc-25-1-default-run-3
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_default

  nvhpc-25-1-default-run-5:
    name: NVHPC 25.1 / default / run 5
    needs: nvhpc-25-1-default-run-4
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_default

  nvhpc-25-1-default-run-6:
    name: NVHPC 25.1 / default / run 6
    needs: nvhpc-25-1-default-run-5
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_default

  nvhpc-25-1-default-run-7:
    name: NVHPC 25.1 / default / run 7
    needs: nvhpc-25-1-default-run-6
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_default

  nvhpc-25-1-default-run-8:
    name: NVHPC 25.1 / default / run 8
    needs: nvhpc-25-1-default-run-7
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_default

  nvhpc-25-1-tp-haswell-run-1:
    name: NVHPC 25.1 / tp-haswell / run 1
    uses: ./.github/workflows/nvhpc-test.yml
    with: &nvhpc_25_1_tp_haswell
      nvhpc: "25.1"
      image: nvcr.io/nvidia/nvhpc:25.1-devel-cuda12.6-ubuntu22.04
      variant: tp-haswell
      compile_flags: "-tp=haswell"
      run_env: ""

  nvhpc-25-1-tp-haswell-run-2:
    name: NVHPC 25.1 / tp-haswell / run 2
    needs: nvhpc-25-1-tp-haswell-run-1
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_tp_haswell

  nvhpc-25-1-tp-haswell-run-3:
    name: NVHPC 25.1 / tp-haswell / run 3
    needs: nvhpc-25-1-tp-haswell-run-2
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_tp_haswell

  nvhpc-25-1-tp-haswell-run-4:
    name: NVHPC 25.1 / tp-haswell / run 4
    needs: nvhpc-25-1-tp-haswell-run-3
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_tp_haswell

  nvhpc-25-1-tp-haswell-run-5:
    name: NVHPC 25.1 / tp-haswell / run 5
    needs: nvhpc-25-1-tp-haswell-run-4
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_tp_haswell

  nvhpc-25-1-tp-haswell-run-6:
    name: NVHPC 25.1 / tp-haswell / run 6
    needs: nvhpc-25-1-tp-haswell-run-5
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_tp_haswell

  nvhpc-25-1-tp-haswell-run-7:
    name: NVHPC 25.1 / tp-haswell / run 7
    needs: nvhpc-25-1-tp-haswell-run-6
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_tp_haswell

  nvhpc-25-1-tp-haswell-run-8:
    name: NVHPC 25.1 / tp-haswell / run 8
    needs: nvhpc-25-1-tp-haswell-run-7
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_tp_haswell

  nvhpc-25-1-mth-iarch-avx2-run-1:
    name: NVHPC 25.1 / mth-iarch-avx2 / run 1
    uses: ./.github/workflows/nvhpc-test.yml
    with: &nvhpc_25_1_mth_iarch_avx2
      nvhpc: "25.1"
      image: nvcr.io/nvidia/nvhpc:25.1-devel-cuda12.6-ubuntu22.04
      variant: mth-iarch-avx2
      compile_flags: ""
      run_env: "MTH_I_ARCH=avx2"

  nvhpc-25-1-mth-iarch-avx2-run-2:
    name: NVHPC 25.1 / mth-iarch-avx2 / run 2
    needs: nvhpc-25-1-mth-iarch-avx2-run-1
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_mth_iarch_avx2

  nvhpc-25-1-mth-iarch-avx2-run-3:
    name: NVHPC 25.1 / mth-iarch-avx2 / run 3
    needs: nvhpc-25-1-mth-iarch-avx2-run-2
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_mth_iarch_avx2

  nvhpc-25-1-mth-iarch-avx2-run-4:
    name: NVHPC 25.1 / mth-iarch-avx2 / run 4
    needs: nvhpc-25-1-mth-iarch-avx2-run-3
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_mth_iarch_avx2

  nvhpc-25-1-mth-iarch-avx2-run-5:
    name: NVHPC 25.1 / mth-iarch-avx2 / run 5
    needs: nvhpc-25-1-mth-iarch-avx2-run-4
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_mth_iarch_avx2

  nvhpc-25-1-mth-iarch-avx2-run-6:
    name: NVHPC 25.1 / mth-iarch-avx2 / run 6
    needs: nvhpc-25-1-mth-iarch-avx2-run-5
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_mth_iarch_avx2

  nvhpc-25-1-mth-iarch-avx2-run-7:
    name: NVHPC 25.1 / mth-iarch-avx2 / run 7
    needs: nvhpc-25-1-mth-iarch-avx2-run-6
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_mth_iarch_avx2

  nvhpc-25-1-mth-iarch-avx2-run-8:
    name: NVHPC 25.1 / mth-iarch-avx2 / run 8
    needs: nvhpc-25-1-mth-iarch-avx2-run-7
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_25_1_mth_iarch_avx2

  nvhpc-26-1-default-run-1:
    name: NVHPC 26.1 / default / run 1
    uses: ./.github/workflows/nvhpc-test.yml
    with: &nvhpc_26_1_default
      nvhpc: "26.1"
      image: nvcr.io/nvidia/nvhpc:26.1-devel-cuda13.1-ubuntu22.04
      variant: default
      compile_flags: ""
      run_env: ""

  nvhpc-26-1-default-run-2:
    name: NVHPC 26.1 / default / run 2
    needs: nvhpc-26-1-default-run-1
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_default

  nvhpc-26-1-default-run-3:
    name: NVHPC 26.1 / default / run 3
    needs: nvhpc-26-1-default-run-2
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_default

  nvhpc-26-1-default-run-4:
    name: NVHPC 26.1 / default / run 4
    needs: nvhpc-26-1-default-run-3
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_default

  nvhpc-26-1-default-run-5:
    name: NVHPC 26.1 / default / run 5
    needs: nvhpc-26-1-default-run-4
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_default

  nvhpc-26-1-default-run-6:
    name: NVHPC 26.1 / default / run 6
    needs: nvhpc-26-1-default-run-5
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_default

  nvhpc-26-1-default-run-7:
    name: NVHPC 26.1 / default / run 7
    needs: nvhpc-26-1-default-run-6
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_default

  nvhpc-26-1-default-run-8:
    name: NVHPC 26.1 / default / run 8
    needs: nvhpc-26-1-default-run-7
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_default

  nvhpc-26-1-tp-haswell-run-1:
    name: NVHPC 26.1 / tp-haswell / run 1
    uses: ./.github/workflows/nvhpc-test.yml
    with: &nvhpc_26_1_tp_haswell
      nvhpc: "26.1"
      image: nvcr.io/nvidia/nvhpc:26.1-devel-cuda13.1-ubuntu22.04
      variant: tp-haswell
      compile_flags: "-tp=haswell"
      run_env: ""

  nvhpc-26-1-tp-haswell-run-2:
    name: NVHPC 26.1 / tp-haswell / run 2
    needs: nvhpc-26-1-tp-haswell-run-1
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_tp_haswell

  nvhpc-26-1-tp-haswell-run-3:
    name: NVHPC 26.1 / tp-haswell / run 3
    needs: nvhpc-26-1-tp-haswell-run-2
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_tp_haswell

  nvhpc-26-1-tp-haswell-run-4:
    name: NVHPC 26.1 / tp-haswell / run 4
    needs: nvhpc-26-1-tp-haswell-run-3
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_tp_haswell

  nvhpc-26-1-tp-haswell-run-5:
    name: NVHPC 26.1 / tp-haswell / run 5
    needs: nvhpc-26-1-tp-haswell-run-4
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_tp_haswell

  nvhpc-26-1-tp-haswell-run-6:
    name: NVHPC 26.1 / tp-haswell / run 6
    needs: nvhpc-26-1-tp-haswell-run-5
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_tp_haswell

  nvhpc-26-1-tp-haswell-run-7:
    name: NVHPC 26.1 / tp-haswell / run 7
    needs: nvhpc-26-1-tp-haswell-run-6
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_tp_haswell

  nvhpc-26-1-tp-haswell-run-8:
    name: NVHPC 26.1 / tp-haswell / run 8
    needs: nvhpc-26-1-tp-haswell-run-7
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_tp_haswell

  nvhpc-26-1-mth-iarch-avx2-run-1:
    name: NVHPC 26.1 / mth-iarch-avx2 / run 1
    uses: ./.github/workflows/nvhpc-test.yml
    with: &nvhpc_26_1_mth_iarch_avx2
      nvhpc: "26.1"
      image: nvcr.io/nvidia/nvhpc:26.1-devel-cuda13.1-ubuntu22.04
      variant: mth-iarch-avx2
      compile_flags: ""
      run_env: "MTH_I_ARCH=avx2"

  nvhpc-26-1-mth-iarch-avx2-run-2:
    name: NVHPC 26.1 / mth-iarch-avx2 / run 2
    needs: nvhpc-26-1-mth-iarch-avx2-run-1
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_mth_iarch_avx2

  nvhpc-26-1-mth-iarch-avx2-run-3:
    name: NVHPC 26.1 / mth-iarch-avx2 / run 3
    needs: nvhpc-26-1-mth-iarch-avx2-run-2
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_mth_iarch_avx2

  nvhpc-26-1-mth-iarch-avx2-run-4:
    name: NVHPC 26.1 / mth-iarch-avx2 / run 4
    needs: nvhpc-26-1-mth-iarch-avx2-run-3
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_mth_iarch_avx2

  nvhpc-26-1-mth-iarch-avx2-run-5:
    name: NVHPC 26.1 / mth-iarch-avx2 / run 5
    needs: nvhpc-26-1-mth-iarch-avx2-run-4
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_mth_iarch_avx2

  nvhpc-26-1-mth-iarch-avx2-run-6:
    name: NVHPC 26.1 / mth-iarch-avx2 / run 6
    needs: nvhpc-26-1-mth-iarch-avx2-run-5
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_mth_iarch_avx2

  nvhpc-26-1-mth-iarch-avx2-run-7:
    name: NVHPC 26.1 / mth-iarch-avx2 / run 7
    needs: nvhpc-26-1-mth-iarch-avx2-run-6
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_mth_iarch_avx2

  nvhpc-26-1-mth-iarch-avx2-run-8:
    name: NVHPC 26.1 / mth-iarch-avx2 / run 8
    needs: nvhpc-26-1-mth-iarch-avx2-run-7
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_1_mth_iarch_avx2

  nvhpc-26-3-default-run-1:
    name: NVHPC 26.3 / default / run 1
    uses: ./.github/workflows/nvhpc-test.yml
    with: &nvhpc_26_3_default
      nvhpc: "26.3"
      image: nvcr.io/nvidia/nvhpc:26.3-devel-cuda13.1-ubuntu22.04
      variant: default
      compile_flags: ""
      run_env: ""

  nvhpc-26-3-default-run-2:
    name: NVHPC 26.3 / default / run 2
    needs: nvhpc-26-3-default-run-1
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_default

  nvhpc-26-3-default-run-3:
    name: NVHPC 26.3 / default / run 3
    needs: nvhpc-26-3-default-run-2
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_default

  nvhpc-26-3-default-run-4:
    name: NVHPC 26.3 / default / run 4
    needs: nvhpc-26-3-default-run-3
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_default

  nvhpc-26-3-default-run-5:
    name: NVHPC 26.3 / default / run 5
    needs: nvhpc-26-3-default-run-4
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_default

  nvhpc-26-3-default-run-6:
    name: NVHPC 26.3 / default / run 6
    needs: nvhpc-26-3-default-run-5
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_default

  nvhpc-26-3-default-run-7:
    name: NVHPC 26.3 / default / run 7
    needs: nvhpc-26-3-default-run-6
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_default

  nvhpc-26-3-default-run-8:
    name: NVHPC 26.3 / default / run 8
    needs: nvhpc-26-3-default-run-7
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_default

  nvhpc-26-3-tp-haswell-run-1:
    name: NVHPC 26.3 / tp-haswell / run 1
    uses: ./.github/workflows/nvhpc-test.yml
    with: &nvhpc_26_3_tp_haswell
      nvhpc: "26.3"
      image: nvcr.io/nvidia/nvhpc:26.3-devel-cuda13.1-ubuntu22.04
      variant: tp-haswell
      compile_flags: "-tp=haswell"
      run_env: ""

  nvhpc-26-3-tp-haswell-run-2:
    name: NVHPC 26.3 / tp-haswell / run 2
    needs: nvhpc-26-3-tp-haswell-run-1
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_tp_haswell

  nvhpc-26-3-tp-haswell-run-3:
    name: NVHPC 26.3 / tp-haswell / run 3
    needs: nvhpc-26-3-tp-haswell-run-2
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_tp_haswell

  nvhpc-26-3-tp-haswell-run-4:
    name: NVHPC 26.3 / tp-haswell / run 4
    needs: nvhpc-26-3-tp-haswell-run-3
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_tp_haswell

  nvhpc-26-3-tp-haswell-run-5:
    name: NVHPC 26.3 / tp-haswell / run 5
    needs: nvhpc-26-3-tp-haswell-run-4
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_tp_haswell

  nvhpc-26-3-tp-haswell-run-6:
    name: NVHPC 26.3 / tp-haswell / run 6
    needs: nvhpc-26-3-tp-haswell-run-5
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_tp_haswell

  nvhpc-26-3-tp-haswell-run-7:
    name: NVHPC 26.3 / tp-haswell / run 7
    needs: nvhpc-26-3-tp-haswell-run-6
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_tp_haswell

  nvhpc-26-3-tp-haswell-run-8:
    name: NVHPC 26.3 / tp-haswell / run 8
    needs: nvhpc-26-3-tp-haswell-run-7
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_tp_haswell

  nvhpc-26-3-mth-iarch-avx2-run-1:
    name: NVHPC 26.3 / mth-iarch-avx2 / run 1
    uses: ./.github/workflows/nvhpc-test.yml
    with: &nvhpc_26_3_mth_iarch_avx2
      nvhpc: "26.3"
      image: nvcr.io/nvidia/nvhpc:26.3-devel-cuda13.1-ubuntu22.04
      variant: mth-iarch-avx2
      compile_flags: ""
      run_env: "MTH_I_ARCH=avx2"

  nvhpc-26-3-mth-iarch-avx2-run-2:
    name: NVHPC 26.3 / mth-iarch-avx2 / run 2
    needs: nvhpc-26-3-mth-iarch-avx2-run-1
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_mth_iarch_avx2

  nvhpc-26-3-mth-iarch-avx2-run-3:
    name: NVHPC 26.3 / mth-iarch-avx2 / run 3
    needs: nvhpc-26-3-mth-iarch-avx2-run-2
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_mth_iarch_avx2

  nvhpc-26-3-mth-iarch-avx2-run-4:
    name: NVHPC 26.3 / mth-iarch-avx2 / run 4
    needs: nvhpc-26-3-mth-iarch-avx2-run-3
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_mth_iarch_avx2

  nvhpc-26-3-mth-iarch-avx2-run-5:
    name: NVHPC 26.3 / mth-iarch-avx2 / run 5
    needs: nvhpc-26-3-mth-iarch-avx2-run-4
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_mth_iarch_avx2

  nvhpc-26-3-mth-iarch-avx2-run-6:
    name: NVHPC 26.3 / mth-iarch-avx2 / run 6
    needs: nvhpc-26-3-mth-iarch-avx2-run-5
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_mth_iarch_avx2

  nvhpc-26-3-mth-iarch-avx2-run-7:
    name: NVHPC 26.3 / mth-iarch-avx2 / run 7
    needs: nvhpc-26-3-mth-iarch-avx2-run-6
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_mth_iarch_avx2

  nvhpc-26-3-mth-iarch-avx2-run-8:
    name: NVHPC 26.3 / mth-iarch-avx2 / run 8
    needs: nvhpc-26-3-mth-iarch-avx2-run-7
    uses: ./.github/workflows/nvhpc-test.yml
    with: *nvhpc_26_3_mth_iarch_avx2
